POST http://localhost:8080/api/signup
Content-Type: application/json

{
    "firstName":"John",
    "middleName":"D",
    "lastName":"Doe",
    "idNumber":"20-02366",
    "contactNumber":"09393805099",
    "email":"lkji@gmail.com",
    "password":"password",
    "isTeacher":false

}